# Generated by Django 3.0.3 on 2020-03-03 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake', models.CharField(max_length=255)),
                ('filling', models.CharField(blank=True, max_length=255, null=True)),
                ('frosting', models.CharField(blank=True, max_length=255, null=True)),
                ('flavour', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(default='1 pound', max_length=255)),
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Happy Birthday', max_length=255)),
                ('Shape', models.CharField(choices=[('Rectangle', 'Rectangle'), ('Round', 'Round')], default='Round', max_length=255)),
                ('eggless', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('sugerless', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('pickupdate', models.DateField()),
                ('timetodeliver', models.TimeField()),
                ('deliverylocation', models.CharField(blank=True, max_length=255)),
                ('mobileno', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cakeorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='cake.Cake')),
            ],
        ),
    ]
