# Generated by Django 3.0.3 on 2020-03-13 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake', models.CharField(max_length=255)),
                ('filling', models.CharField(blank=True, max_length=255, null=True)),
                ('frosting', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='static')),
                ('base_cost', models.DecimalField(decimal_places=2, help_text='per pound', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FlavorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decoration', models.CharField(help_text='Eg:Happy Bithday', max_length=255)),
                ('Shape', models.CharField(choices=[('Rectangle', 'Rectangle'), ('Round', 'Round')], default='Round', max_length=255)),
                ('eggless', models.BooleanField()),
                ('accessories', models.BooleanField()),
                ('sugerless', models.BooleanField()),
                ('pickupdate', models.DateField()),
                ('timetodeliver', models.TimeField()),
                ('deliverylocation', models.CharField(blank=True, max_length=255)),
                ('contactno', models.PositiveIntegerField()),
                ('no_of_pounds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='[[base_cost * pounds] + flavor_name * pounds] + Eggless + Accessories + sugerless]*quantity', max_digits=10)),
                ('status', models.CharField(choices=[('r', 'Received'), ('p', 'Processing'), ('d', 'delivery')], max_length=1)),
                ('cakeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='cake.Cake')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cake_category', to='cake.Category')),
                ('flavor_type', models.ManyToManyField(related_name='cake_flavor_type', to='cake.FlavorType')),
            ],
        ),
        migrations.AddField(
            model_name='cake',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake.Category'),
        ),
        migrations.AddField(
            model_name='cake',
            name='flavor_type',
            field=models.ManyToManyField(to='cake.FlavorType'),
        ),
    ]
