# Generated by Django 3.0.3 on 2020-03-15 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_auto_20200313_0659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-pickupdate',)},
        ),
        migrations.AlterField(
            model_name='cake',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='cake.Category'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='flavor_type',
            field=models.ManyToManyField(related_name='flavor', to='cake.FlavorType'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('r', 'Received'), ('p', 'Processing'), ('d', 'delivery'), ('c', 'cancelled')], max_length=1),
        ),
    ]
