# Generated by Django 3.0.3 on 2020-03-15 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0004_auto_20200315_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_cake', to='cake.Category'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='flavor_type',
            field=models.ManyToManyField(related_name='flavor_cake', to='cake.FlavorType'),
        ),
    ]
