# Generated by Django 3.0.3 on 2020-03-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0005_auto_20200315_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='cake/'),
        ),
    ]
