# Generated by Django 3.0.3 on 2020-03-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0006_auto_20200315_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('r', 'Received'), ('p', 'Processing'), ('d', 'delivery'), ('c', 'cancelled')], default='r', max_length=1),
        ),
    ]
