# Generated by Django 3.0.3 on 2020-03-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0007_auto_20200315_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contactno',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='decoration',
            field=models.CharField(blank=True, help_text='Eg:Happy Bithday', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='flavor_type',
            field=models.ManyToManyField(blank=True, related_name='cake_flavor_type', to='cake.FlavorType'),
        ),
        migrations.AlterField(
            model_name='order',
            name='no_of_pounds',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
