# Generated by Django 3.0.3 on 2020-03-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0008_auto_20200316_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contactno',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='decoration',
            field=models.CharField(blank=True, help_text='Eg:Happy Bithday', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='flavor_type',
            field=models.ManyToManyField(blank=True, null=True, related_name='cake_flavor_type', to='cake.FlavorType'),
        ),
    ]
