# Generated by Django 3.0.3 on 2020-03-17 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0009_auto_20200316_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='flavor_type',
        ),
        migrations.AddField(
            model_name='order',
            name='flavor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cake_flavor_type', to='cake.FlavorType'),
        ),
    ]
